# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-notifications

# >> macros
# << macros

Summary:    Notifications plugin for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-notifications
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-notifications.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
Provides:   nemo-qml-plugins-notifications > 0.3.20
Obsoletes:   nemo-qml-plugins-notifications <= 0.3.20

%description
%{summary}.

%package devel
Summary:    Notifications support for C++ applications
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/notifications/libnemonotifications.so
%{_libdir}/qt4/imports/org/nemomobile/notifications/qmldir
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/nemo-qml-plugins/notifications/*.h
%{_libdir}/pkgconfig/nemonotifications.pc
# >> files devel
# << files devel
